# ~/.config/hypr/hyprlock.conf

# Background settings
background {
    monitor =
    path = screenshot
    blur_passes = 3
}

# General appearance
general {
    hide_cursor = true
    grace = 0
    no_fade_in = false
}

input-field {
    monitor =
    size = 200, 40
    outline_thickness = 1
    dots_size = 0.2
    dots_spacing = 0.15
    dots_center = true
    fade_on_empty = false
    font_family = "DejaVu Sans Mono"
    font_size = 10
    placeholder_text = <i>sådan</i>
    inner_color = rgba(22,23,24,0.8)
    outer_color = rgba(253,106,192,0.9)
    outline_color = rgba(68,68,68,0.9)
    font_color = rgba(196,200,197,0.9)
    position = 0, -110
    halign = center
    valign = center
    rounding = 0
}

image {
    monitor =
    path = /home/bomba/Pictures/logo/logo.png
    size = 200
    rounding = 0
    border_color = rgba(68,68,68,0.9)
    border_size = 1
    position = 0, 40
    halign = center
    valign = center
}
