# Original configuration with embedded display and one extra monitor
monitor=eDP-1,1920x1080,0x0,1
monitor=DP-1,1920x1080,1920x-800,1

# "Desktop" setup, since I broke the screen
#monitor=eDP-1,disable
#monitor=DP-1,1920x1080,0x0,1
