# Font
font_family      DejaVu Sans Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10.0

background            #161718
foreground            #c4c8c5

cursor                #d0d0d0

color0                #241f31
color1                #c01c28
color2                #2ec27e
color3                #f5c211
color4                #1e78e4
color5                #9841bb
color6                #0ab9dc
color7                #c0bfbc
color8                #5e5c64
color9                #ed333b
color10               #57e389
color11               #f8e45c
color12               #51a1ff
color13               #c061cb
color14               #4fd2fd
color15               #f6f5f4

selection_background  #444444
selection_foreground  #161718

window_padding_width 4

# Keybindings
map ctrl+alt+f launch --type=overlay --cwd=current yazi
